# permissions for end users to view multisecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: multisecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secret-operator
    app.kubernetes.io/part-of: secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: multisecret-viewer-role
rules:
- apiGroups:
  - multi.ddnw.ml
  resources:
  - multisecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multi.ddnw.ml
  resources:
  - multisecrets/status
  verbs:
  - get
